-- Full project restoration SQL
-- This script inserts all 15 projects with complete original data
-- Run this AFTER connecting to the DB (local or pgAdmin)

DELETE FROM proyectos WHERE id IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16);

INSERT INTO proyectos (id, nombre, descripcion_corta, tecnologias_usadas, integrantes_detalle, complejidad_nivel, vistas_contador, disponible_para_patrocinio, miembros_disponibles, cuenta_bancaria) VALUES
(1, 'Proyecto A', 'App web para gestión', 'React, Spring Boot', '[{"nombre": "Ana Perez", "carrera": "Diseño y Desarrollo del Software", "ciclo": 4}, {"nombre": "Luis Gomez", "carrera": "Diseño y Desarrollo del Software", "ciclo": 4}]', 1, 16, false, 3, '0123456789'),
(2, 'Proyecto B', 'Sistema de inventario', 'Java, PostgreSQL', '[{"nombre": "Carlos Ruiz", "carrera": "Diseño y Desarrollo del Software", "ciclo": 4}]', 3, 8, false, 2, '0123456789'),
(3, 'Proyecto C', 'App móvil educativa', 'React Native, Firebase', '[{"nombre": "María Soto", "carrera": "Diseño y Desarrollo del Software", "ciclo": 4}]', 1, 20, false, 1, '0123456789'),
(4, 'Gestor de Proyectos Web', 'Plataforma web para gestión colaborativa de proyectos estudiantiles', 'React, Spring Boot, PostgreSQL', 'Ana Perez, Luis Gomez, Roberto Silva', 3, 46, false, 0, '0123456789'),
(5, 'App Móvil de Inventario', 'Aplicación móvil para control de stocks en tiempo real', 'React Native, Firebase, Java', 'Carlos Ruiz, Mariana López', 2, 34, true, 2, '0123456789'),
(6, 'Dashboard Analytics Educativo', 'Sistema de analítica para visualizar datos de desempeño estudiantil', 'React, D3.js, Django, PostgreSQL', 'María Soto, José Martín', 4, 68, false, 1, '0123456789'),
(7, 'API REST Microservicios', 'Arquitectura de microservicios con seguridad OAuth2 y JWT', 'Spring Boot, Kubernetes, PostgreSQL', 'David Chen, Patricia Gómez', 4, 31, true, 2, '0123456789'),
(8, 'Editor Código Colaborativo', 'Editor de código en tiempo real para pares de programadores', 'Vue.js, Node.js, WebSocket', 'Claudia Mendez, Franco Díaz', 3, 53, true, 2, '0123456789'),
(9, 'Gestor de Proyectos Web', 'Plataforma web para gestión colaborativa', 'React, Spring Boot', 'Ana, Luis', 3, 46, true, 1, '0123456789'),
(10, 'App Móvil Inventario', 'Control de stocks en tiempo real', 'React Native, Firebase', 'Carlos, Mariana', 2, 33, true, 2, '0123456789'),
(11, 'Dashboard Analytics', 'Sistema de analítica educativo', 'React, D3.js, Django', 'María, José', 4, 69, false, 0, '0123456789'),
(12, 'ParkingTec: Gestor de Estacionamiento Inteligente', 'Sistema de control de acceso y ocupación en tiempo real para estacionamientos usando sensores y MQTT.', 'ESP32, Sensor Ultrasónico, Servomotor, MQTT, Node-RED, Certificados SSL', '[{"nombre": "Chávez Arianna", "carrera": "Diseño y Desarrollo del Software", "ciclo": 4}, {"nombre": "Velasco Valeria", "carrera": "Diseño y Desarrollo del Software", "ciclo": 4}, {"nombre": "Ccarita Veronica", "carrera": "Diseño y Desarrollo del Software", "ciclo": 4}, {"nombre": "Medina Diego", "carrera": "Diseño y Desarrollo del Software", "ciclo": 4}]', 2, 0, true, 2, '21598016589050'),
(13, 'Campus Virtual 3D: Tecsup XR', 'Modelo inmersivo del campus de Tecsup utilizando realidad virtual para visitas guiadas y simulación de laboratorios.', 'Blender, Unity, Spatial, WebXR, C#', '[{"nombre": "Chávez Arianna", "carrera": "Diseño y Desarrollo del Software", "ciclo": 4}, {"nombre": "Velasco Valeria", "carrera": "Diseño y Desarrollo del Software", "ciclo": 4}, {"nombre": "Ccarita Veronica", "carrera": "Diseño y Desarrollo del Software", "ciclo": 4}, {"nombre": "Medina Diego", "carrera": "Diseño y Desarrollo del Software", "ciclo": 4}, {"nombre": "Ojeda Kevin", "carrera": "Diseño y Desarrollo del Software", "ciclo": 4}]', 3, 0, true, 3, '4214100327895365'),
(14, 'Control de LED con Arduino', 'Sistema simple de control de LED RGB mediante botones y Arduino.', 'Arduino, C++, Protoboard, LED RGB', '[{"nombre": "García Juan", "carrera": "Diseño y Desarrollo del Software", "ciclo": 1}]', 1, 0, true, 3, '0123456789'),
(15, 'AlphaKids: Plataforma interactiva para aprendizaje temprano', 'Aplicación móvil educativa orientada a niños de educación inicial, diseñada para reforzar conceptos básicos mediante actividades interactivas, almacenamiento en la nube y seguimiento docente.', 'Android Studio, Firebase (Authentication, Firestore, Storage, etc)', '[{"nombre": "Llanos Garcia, Diego Raúl", "carrera": "Diseño y Desarrollo del Software", "ciclo": 4}, {"nombre": "Rojas Juño, Guiller Breyneer", "carrera": "Diseño y Desarrollo del Software", "ciclo": 4}, {"nombre": "Sullca Huamán, Junior Benjamin", "carrera": "Diseño y Desarrollo del Software", "ciclo": 4}, {"nombre": "Zinanyuca Calcina, Gerald Brand", "carrera": "Diseño y Desarrollo del Software", "ciclo": 4}]', 2, 0, false, 0, '0123456789'),
(16, 'AirGuardNet: Sistema Wearable IoT para Monitoreo de Polvo Respirable en Minería', 'Dispositivo portátil inteligente que mide PM2.5 y PM10 en tiempo real, enviando alertas a un dashboard web para prevenir enfermedades pulmonares en trabajadores mineros.', 'ESP32, Sensor óptico PMS5003, LEDs de alerta, Buzzer, Next.js, Django, Neon (PostgreSQL)', '[{"nombre": "Alca Peralta Antony Andrew", "carrera": "Diseño y Desarrollo del Software", "ciclo": 4}, {"nombre": "Sapacayo Mamani Yordan Romel", "carrera": "Diseño y Desarrollo del Software", "ciclo": 4}, {"nombre": "Velasco Sencia Valeria Angela", "carrera": "Diseño y Desarrollo del Software", "ciclo": 4}, {"nombre": "Vilca Caza Jorge Thomas", "carrera": "Diseño y Desarrollo del Software", "ciclo": 4}]', 2, 0, true, 3, '0123456789');
